export const identity = { logo: `${import.meta.env.BASE_URL}images/nutrir-logo.svg`, hero: 'https://images.unsplash.com/photo-1608671071793-db93efcf33df?auto=format&fit=crop&w=1800&q=86', name: 'Nutrir', description: 'Empresa Júnior de Nutrição de Ruminantes' };
export const hero = {title:'Nutrição de ruminantes com base técnica e aplicação prática.', text:'A Nutrir é uma Empresa Júnior universitária que conecta conhecimento acadêmico a soluções práticas em nutrição de ruminantes, contribuindo para sistemas produtivos mais eficientes e sustentáveis.'};
export const navigation = [['Início','inicio'],['Quem Somos','quem-somos'],['Serviços','servicos'],['Como Funciona','como-funciona'],['Diferenciais','diferenciais'],['Equipe','equipe'],['Contato','contato']];
export const credibility = [ ['university','Empresa Júnior universitária','Formação, propósito e atuação acadêmica.'],['science','Base científica','Soluções fundamentadas em conhecimento atualizado.'],['people','Atendimento personalizado','Recomendações adaptadas à realidade de cada cliente.'],['field','Projetos aplicados no campo','Atuação prática do diagnóstico ao acompanhamento.'] ];
export const services = [
 {icon:'pasture',title:'Solos e Pastagens',text:'Coleta de solo para análise, orientação de correção, escolha de sementes e manejo de pastagens.',detail:'Coletamos amostras de solo e encaminhamos para análise em laboratório. O trabalho contempla orientação de calagem e gessagem quando necessárias, seleção de sementes e planejamento do manejo de pastagens.'},
 {icon:'health',title:'Manejo Sanitário e Reprodutivo',text:'Protocolos de entrada de animais, calendário vacinal, análise de água, estação de monta e testes de mastite.',detail:'Apoio ao planejamento sanitário e reprodutivo do rebanho, conforme a finalidade da produção. Os serviços incluem protocolos para novos animais, calendário de vacinação, avaliação da água, estação de monta e testes para identificação de mastite.'},
 {icon:'facilities',title:'Dimensionamento de Instalações',text:'Planejamento de piquetes, cochos, bebedouros, mangueiros e barracões para gado leiteiro.',detail:'O dimensionamento considera a área disponível, os tipos de solo, a topografia e as características existentes na propriedade, com foco na organização e no manejo do rebanho.'},
 {icon:'diet',title:'Nutrição Animal',text:'Formulação de rações e dietas, estudo da viabilidade de insumos e análise bromatológica.',detail:'Formulação de acordo com as exigências nutricionais dos animais, avaliação de alimentos e estudo dos insumos disponíveis na região, considerando preço e logística. A análise bromatológica subsidia o conhecimento da composição e do valor nutricional dos alimentos.'},
 {icon:'economy',title:'Viabilidade Econômica',text:'Análise de custos e benefícios das escolhas produtivas da propriedade.',detail:'Avaliação da viabilidade de fatores como fase de produção — cria, recria ou engorda —, lotação, raça e região, considerando os custos e os benefícios para a propriedade.'},
 {icon:'production',title:'Maximização da Produção',text:'Planejamento da eficiência e introdução de técnicas e tecnologias para melhorar a produção.',detail:'Identificação de oportunidades de melhoria na eficiência da fazenda, com aplicação de tecnologias e técnicas alinhadas à qualidade da produção e à renda do produtor.'}
];
export const process = [['Diagnóstico','Entendimento da realidade, objetivos e principais desafios.'],['Análise','Avaliação das informações disponíveis e identificação de oportunidades.'],['Recomendação','Desenvolvimento de uma proposta técnica personalizada e viável.'],['Acompanhamento','Monitoramento dos resultados e possíveis ajustes.']];
export const differences = [['university','Vínculo universitário','Atuação inserida em ambiente acadêmico e técnico.'],['people','Equipe orientada','Estudantes capacitados e acompanhados por professores e profissionais.'],['field','Foco em soluções aplicáveis','Recomendações alinhadas à realidade prática do campo.'],['quality','Atuação técnica','Compromisso com qualidade, ética e desenvolvimento da pecuária.']];
export const team = Array.from({length:4},(_,i)=>({id:i+1,name:'Nome a preencher',role:'Cargo a preencher',photo:null}));
export const contacts = {whatsapp:'5514998867015',whatsappLabel:'(14) 99886-7015',email:'diretorianutrir@gmail.com',instagram:'https://www.instagram.com/ejnutrir/',instagramLabel:'@ejnutrir',linkedin:'',linkedinLabel:'Nutrir Empresa Júnior',address:''};
export const sectionText = {aboutTitle:'Conhecimento acadêmico, atuação no campo.',about:'Desde 2003, a Nutrir aproxima o conhecimento agropecuário da realidade do campo. Como Empresa Júnior, desenvolve a experiência profissional e empresarial dos estudantes e atende produtores com serviços em nutrição, manejo e planejamento da produção.',team:'A Nutrir é formada por estudantes comprometidos com a nutrição animal e com a aplicação prática do conhecimento.'};
export const principles = [
 ['Missão','Consolidar a experiência profissional e empresarial no meio acadêmico, formando profissionais mais capacitados para o mercado de trabalho, atendendo o cliente com ciência e compartilhando conhecimento agropecuário com a sociedade.'],
 ['Visão','Ser uma empresa de referência em seus projetos e conhecimento, entregando serviços de qualidade e acessíveis.'],
 ['Valores','Parceria, ética, conhecimento e força.']
];
