import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Menu,X,Mail,Instagram,MessageCircleMore,UserRound,MapPin,Plus,Minus,Linkedin} from 'lucide-react';
import {identity,hero,navigation,credibility,services,process,differences,team,contacts,sectionText,principles} from './data';
import './styles.css';
import Icon from './Icon';
function Brand(){return <a className="brand" href="#inicio" aria-label="Nutrir — Início"><img src={identity.logo} alt="Nutrir" width="76" height="62"/><span>Empresa Júnior de<br/>Nutrição de Ruminantes</span></a>}
function App(){const [menu,setMenu]=useState(false),[allTeam,setAllTeam]=useState(false);const menuButton=useRef(null);useEffect(()=>{function close(e){if(e.key==='Escape'){setMenu(false);menuButton.current?.focus()}}window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><header><div className="container header-inner"><Brand/><nav aria-label="Navegação principal" id="main-menu" className={menu?'navigation open':'navigation'}>{navigation.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a className="button mobile-contact" href="#contato" onClick={()=>setMenu(false)}>Fale com a Nutrir <ArrowUpRight size={17}/></a></nav><a className="button header-contact" href="#contato">Fale com a Nutrir <ArrowUpRight size={17}/></a><button ref={menuButton} className="menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} aria-controls="main-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main id="conteudo"><section className="hero" id="inicio"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span/> NUTRIÇÃO DE RUMINANTES</p><h1>{hero.title}</h1><p className="lead">{hero.text}</p><div className="hero-actions"><a className="button" href="#servicos">Conheça nossos serviços <ArrowUpRight size={18}/></a><a className="text-link" href="#contato">Entrar em contato <ArrowRight size={17}/></a></div></div><div className="hero-image"><img src={identity.hero} alt="Bovino Nelore em curral, fotografia ilustrativa de Andrey Câmara" width="1300" height="1100" fetchPriority="high"/><div className="photo-label"><span className="photo-line"/> Nutrição · Manejo · Produção</div></div></div></section>
<section className="credibility" aria-label="Nossa atuação"><div className="container credibility-grid">{credibility.map(([icon,title,text])=><div className="credibility-item" key={title}><Icon name={icon}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
<section className="section about" id="quem-somos"><div className="container"><div className="about-grid"><div><p className="eyebrow">QUEM SOMOS</p><h2>{sectionText.aboutTitle}</h2></div><div><p>{sectionText.about}</p><a className="text-link" href="#equipe">Conheça nossa equipe <ArrowUpRight size={18}/></a></div></div><div className="principles-grid">{principles.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="section services" id="servicos"><div className="container"><div className="section-heading"><div><p className="eyebrow">NOSSOS SERVIÇOS</p><h2>Soluções técnicas para<br className="desktop-break"/> a sua produção</h2></div><p>Atendimento adaptado às necessidades<br className="desktop-break"/> do seu rebanho e do seu projeto.</p></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.title}><div className="card-top"><Icon name={s.icon}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.text}</p><details><summary>Saiba mais <Plus size={17}/></summary><p>{s.detail}</p><a href="#contato" className="text-link">Conversar com a equipe <ArrowUpRight size={16}/></a></details></article>)}</div></div></section>
<section className="section process" id="como-funciona"><div className="container"><p className="eyebrow">COMO FUNCIONA</p><h2>Do diagnóstico aos resultados</h2><ol className="process-grid">{process.map(([title,text],i)=><li key={title}><span className="step-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
<section className="section differences" id="diferenciais"><div className="container differences-layout"><div className="difference-intro"><p className="eyebrow">NOSSOS DIFERENCIAIS</p><h2>Por que escolher<br/>a Nutrir?</h2><div className="diagonal-accent" aria-hidden="true"/></div><div className="difference-grid">{differences.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="section team" id="equipe"><div className="container"><div className="section-heading"><div><p className="eyebrow">QUEM FAZ A NUTRIR</p><h2>Nossa equipe</h2></div><p>{sectionText.team}</p></div><div className="team-grid">{(allTeam?team:team.slice(0,4)).map(member=><article className="team-member" key={member.id}>{member.photo?<img src={member.photo} alt={member.name} width="176" height="176" loading="lazy"/>:<div className="avatar-placeholder"><UserRound strokeWidth={1.5} aria-hidden="true"/><span>Foto a adicionar</span></div>}<h3>{member.name}</h3><p>{member.role}</p></article>)}</div><div className="team-action"><button className="button outline" aria-expanded={allTeam} onClick={()=>setAllTeam(!allTeam)}>{allTeam?'Recolher equipe':'Conheça toda a equipe'} {allTeam?<Minus size={17}/>:<ArrowUpRight size={17}/>}</button>{allTeam&&<p className="team-note" role="status">{team.every(m=>!m.photo)?'Os nomes, cargos e fotos da equipe serão adicionados em breve.':'Todos os integrantes cadastrados estão apresentados acima.'}</p>}</div></div></section>
<section className="contact" id="contato"><div className="container contact-grid"><div><p className="eyebrow">VAMOS CONVERSAR</p><h2>Entre em contato<br/>com a Nutrir</h2><p>Conte para nossa equipe sobre a realidade<br className="desktop-break"/> da sua propriedade ou projeto.</p><a className="button white" href={contacts.whatsapp?`https://wa.me/${contacts.whatsapp}`:'#canais'}>Fale com a Nutrir <ArrowUpRight size={18}/></a></div><div className="contact-channels" id="canais">{[[MessageCircleMore,'WhatsApp',contacts.whatsapp,`https://wa.me/${contacts.whatsapp}`,contacts.whatsappLabel],[Mail,'E-mail',contacts.email,`mailto:${contacts.email}`,contacts.email],[Instagram,'Instagram',contacts.instagram,contacts.instagram,contacts.instagramLabel],[Linkedin,'LinkedIn',contacts.linkedin,contacts.linkedin,contacts.linkedinLabel]].map(([I,label,value,url,display])=><div className="contact-row" key={label}><span className="contact-icon" aria-hidden="true"><I size={23} strokeWidth={1.75}/></span><div><h3>{label}</h3>{value?<a href={url}>{display||value}</a>:<span>{label==='LinkedIn'?contacts.linkedinLabel+' · link a preencher':'Contato a preencher'}</span>}</div>{value&&<a className="channel-arrow" href={url} aria-label={`Abrir ${label}`}><ArrowUpRight/></a>}</div>)}{contacts.address&&<div className="contact-row"><MapPin/><p>{contacts.address}</p></div>}</div></div></section></main>
<footer><div className="container footer-top"><Brand/><div className="footer-links">{navigation.filter((_,i)=>[1,2,5,6].includes(i)).map(([label,id])=><a key={id} href={'#'+id}>{label}</a>)}</div><a className="text-link" href="#canais">Contatos e redes sociais <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} Nutrir. Todos os direitos reservados.</p><p>Empresa Júnior de Nutrição de Ruminantes</p></div></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
